name: Build

on:
  push:
    branch:
        - '**'
    tags-ignore:
        - v*

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build project
        run: dotnet build -c Release