name: Publish NuGet Package

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Create package
        run: dotnet pack Sutro.PathWorks.Plugins.API/Sutro.PathWorks.Plugins.API.csproj -c Release --include-source --include-symbols
      - name: Push package
        run: dotnet nuget push **/*.nupkg
               --skip-duplicate 
               --api-key ${{ secrets.NUGET_API_KEY }}
               --source https://api.nuget.org/v3/index.json